{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.beinteractive.hygate",
    "module": "hygateg-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "hygateg-sdk-1.0.1.aar",
          "url": "hygateg-sdk-1.0.1.aar",
          "size": 111595,
          "sha512": "4f25b50484a0167162fd3ae6015a97ab3e002070c028e34a50b1aed49286556c5491d905879e5cd4e9a638b1a9d37b6bc0d06e7314d3cad2ef695e72ed529f94",
          "sha256": "93ce8832e71770f341d223ccef5aed878bf082b657e6c89cf57d8879a1459770",
          "sha1": "9a19da5fe537be76dacd7a11b429607e85633d31",
          "md5": "7099312cabf9ea5c229b86bd0785f0b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "hygateg-sdk-1.0.1.aar",
          "url": "hygateg-sdk-1.0.1.aar",
          "size": 111595,
          "sha512": "4f25b50484a0167162fd3ae6015a97ab3e002070c028e34a50b1aed49286556c5491d905879e5cd4e9a638b1a9d37b6bc0d06e7314d3cad2ef695e72ed529f94",
          "sha256": "93ce8832e71770f341d223ccef5aed878bf082b657e6c89cf57d8879a1459770",
          "sha1": "9a19da5fe537be76dacd7a11b429607e85633d31",
          "md5": "7099312cabf9ea5c229b86bd0785f0b0"
        }
      ]
    }
  ]
}
